### ISSUE TITLE
wsparcie dla innych bramek ipfs

### ISSUE THREAD

**Issue by ghost** [meehow/2read#4]
lista publicznych bramek 
```
https://ipfs.fooock.com/
```

prosiłbym o dodanie menu w którym można by dodać lub usunąć wybrane bramki,
prosiłbym również o menu w którym można by dodać lub zmienić domyślną bramkę.

**Comment by KonoromiHimaries** [comment]
prosiłbym o dodanie menu w którym można by dodać lub usunąć wybrane bramki

**Comment by meehow** [comment]
Please write in English, so others can also understand the issue.

Selecting the gateway is random at the moment. It would be nice if "best" gateway is selected automatically, but what does it meant "the best gateway"?

**Comment by meehow** [comment]
I added more gateways and fastest one is selected as default.
