### ISSUE TITLE
wiral

### ISSUE THREAD

**Issue by ghost** [meehow/2read#5]
klikając na ikonkę rozszerzenia mogę powielać ten sam artykuł w nieskończoność

przykład
```
https://ipfs.io/ipfs/QmbXEXQEkSA9PULr59NUEBrykHR1Ev9YeBnUTBxEdED9vg/
https://ipfs.io/ipfs/QmY3ZyNH3jWryz1nVoWkni4w94mxyH7zRUFQyaLnuWECG7/
https://ipfs.io/ipfs/QmPYuYgLwtWNvZ6tZUpF3ANyJJ34Q847z54aDApzjgQ8Mq/
```

**Comment by meehow** [comment]
Please write in English, so others can also understand the issue.

Dzięki za raport, ale wydaje mi się że jest to ta sama strona, ale nie do końca załadowana. Zgadza się?
