### ISSUE TITLE
Doesn't seem to work with some Forbes articles

### ISSUE THREAD

**Issue by m-p-3** [meehow/2read#8]
Example: https://www.forbes.com/sites/johnkoetsier/2019/09/02/hong-kong-protestors-using-mesh-messaging-app-china-cant-block-usage-up-3685/#6e5217d3135a

Pressing the 2read icon doesn't seem to accomplish anything. Could it be that the website *infinite scroll* is messing up with the addon?

**Comment by m-p-3** [comment]
Another example: https://www.technologyreview.com/s/613446/the-ambitious-plan-to-make-the-internets-phone-book-more-trustworthy/

**Comment by meehow** [comment]
looks like it works after update :) please confirm
